stages:
  download_data:
    desc: Download data from Kaggle
    cmd: python3 src/data/download.py -tr train.csv -te test.csv -o ./data/raw
    deps:
    - src/data/download.py
    params:
    - competition
    outs:
    - data/raw/test.csv
    - data/raw/train.csv
