stages:
  download_data:
    desc: Download data from Kaggle
    cmd: python3 src/data/download.py -tr train.csv -te test.csv -o ./data/raw
    deps:
    - src/data/download.py
    params:
    - competition
    outs:
    - data/raw/test.csv
    - data/raw/train.csv
  prepare_images:
    desc: Create 2D images from flattened images in numpy array
    cmd: python3 src/data/prepare_img.py -tr data/raw/train.csv -te data/raw/test.csv
      -o ./data/processed/
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/prepare_img.py
    - src/img/transforms.py
    outs:
    - data/processed/test/
    - data/processed/test_mapfile.csv
    - data/processed/test_mean_image.png
    - data/processed/train/
    - data/processed/train_mapfile.csv
    - data/processed/train_mean_image.png
  split_train_dev:
    desc: Split training data into the train and dev sets using stratified K-fold
      cross validation.
    cmd: python3 src/data/split_train_dev.py -tr data/processed/train_mapfile.csv
      -o data/processed/
    deps:
    - data/processed/train_mapfile.csv
    - src/data/split_train_dev.py
    params:
    - random_seed
    - train_test_split
    outs:
    - data/processed/split_train_dev.csv
  train_model:
    desc: Train the specified classifier using the pre-allocated stratified K-fold
      cross validation splits and the current params.yaml settings.
    cmd: python3 src/models/train_model.py -mf data/processed/train_mapfile.csv -cv
      data/processed/split_train_dev.csv
    deps:
    - data/processed/split_train_dev.csv
    - data/processed/train_mapfile.csv
    - src/models/train_model.py
    params:
    - classifier
    - model_params
    - random_seed
    plots:
    - reports/figures/logs.csv
