classifier: simple_mnist
competition: digit-recognizer
drop_cols: null
dtypes: null
feature_eng:
  featurize: false
gpu: false
imputation: null
model_params:
  logistic_regression: null
  naive_bayes: null
  neural_network: null
  random_forest: null
  support_vector_machine: null
  xgboost: null
  cnn:
    epochs: 30
    dropout_rate: 0.5
    learn_rate: 0.01
    optimizer: adam
normalize: null
param_tuning:
  logistic_regression: null
  naive_bayes: null
  neural_network: null
  num_eval: 100
  random_forest: null
  scoring: accuracy
  support_vector_machine: null
predict:
  js_estimator: true
random_seed: 12345
train_test_split:
  n_split: 10
  shuffle: true
  target_class: label
